spring:
  application:
    name: haru-engine

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    haru: INFO